name: DATE
favicon: null
layout_spectrum: 0.63099
typography_spectrum: 0.20623
title: DATE - 3D Architectural Visualization
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8f3'
    - '#d7d8d3'
    - '#222224'
    - '#52534e'
    - '#90918c'
  brandStrength: 0.7038389607332647
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
