name: DATE
favicon: null
layout_spectrum: 0.6861302386969328
typography_spectrum: 0.8138011801056564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7038389607332647
  lightness: 0.2559279380366206
  saturation: 0.6299132867716253
  rhythmicContrast: 0.19881218392401934
purpose: []
